import { Deserializable } from '../../../core/models/deserializable';
import { ToString } from '../../../core/models/to-string';

export class XeroPaymentsModel extends Deserializable implements ToString {
    public idAuto: number;                // for column: "id_auto"
    public id: string;                // for column: "ID"
    public contactname: string;                // for column: "ContactName"
    public emailaddress: string;                // for column: "EmailAddress"
    public poaddressline1: string;                // for column: "POAddressLine1"
    public poaddressline2: string;                // for column: "POAddressLine2"
    public poaddressline3: string;                // for column: "POAddressLine3"
    public poaddressline4: string;                // for column: "POAddressLine4"
    public pocity: string;                // for column: "POCity"
    public poregion: string;                // for column: "PORegion"
    public popostalcode: string;                // for column: "POPostalCode"
    public pocountry: string;                // for column: "POCountry"
    public saaddressline1: string;                // for column: "SAAddressLine1"
    public saaddressline2: string;                // for column: "SAAddressLine2"
    public saaddressline3: string;                // for column: "SAAddressLine3"
    public saaddressline4: string;                // for column: "SAAddressLine4"
    public sacity: string;                // for column: "SACity"
    public saregion: string;                // for column: "SARegion"
    public sapostalcode: string;                // for column: "SAPostalCode"
    public sacountry: string;                // for column: "SACountry"
    public invoicenumber: string;                // for column: "InvoiceNumber"
    public reference: string;                // for column: "Reference"
    public invoicedate: string;                // for column: "InvoiceDate"
    public duedate: string;                // for column: "DueDate"
    public planneddate: string;                // for column: "PlannedDate"
    public total: number;                // for column: "Total"
    public taxtotal: string;                // for column: "TaxTotal"
    public invoiceamountpaid: string;                // for column: "InvoiceAmountPaid"
    public invoiceamountdue: boolean;                // for column: "InvoiceAmountDue"
    public inventoryitemcode: string;                // for column: "InventoryItemCode"
    public description: string;                // for column: "Description"
    public quantity: string;                // for column: "Quantity"
    public unitamount: number;                // for column: "UnitAmount"
    public discount: string;                // for column: "Discount"
    public lineamount: number;                // for column: "LineAmount"
    public accountcode: number;                // for column: "AccountCode"
    public taxtype: string;                // for column: "TaxType"
    public taxamount: string;                // for column: "TaxAmount"
    public trackingname1: string;                // for column: "TrackingName1"
    public trackingoption1: string;                // for column: "TrackingOption1"
    public trackingname2: string;                // for column: "TrackingName2"
    public trackingoption2: string;                // for column: "TrackingOption2"
    public currency: string;                // for column: "Currency"
    public type: string;                // for column: "Type"
    public sent: string;                // for column: "Sent"
    public status: string;                // for column: "Status"

    getKeys() {
        return [
            'idAuto',                // for column: "id_auto"
            'id',                // for column: "ID"
            'contactname',                // for column: "ContactName"
            'emailaddress',                // for column: "EmailAddress"
            'poaddressline1',                // for column: "POAddressLine1"
            'poaddressline2',                // for column: "POAddressLine2"
            'poaddressline3',                // for column: "POAddressLine3"
            'poaddressline4',                // for column: "POAddressLine4"
            'pocity',                // for column: "POCity"
            'poregion',                // for column: "PORegion"
            'popostalcode',                // for column: "POPostalCode"
            'pocountry',                // for column: "POCountry"
            'saaddressline1',                // for column: "SAAddressLine1"
            'saaddressline2',                // for column: "SAAddressLine2"
            'saaddressline3',                // for column: "SAAddressLine3"
            'saaddressline4',                // for column: "SAAddressLine4"
            'sacity',                // for column: "SACity"
            'saregion',                // for column: "SARegion"
            'sapostalcode',                // for column: "SAPostalCode"
            'sacountry',                // for column: "SACountry"
            'invoicenumber',                // for column: "InvoiceNumber"
            'reference',                // for column: "Reference"
            'invoicedate',                // for column: "InvoiceDate"
            'duedate',                // for column: "DueDate"
            'planneddate',                // for column: "PlannedDate"
            'total',                // for column: "Total"
            'taxtotal',                // for column: "TaxTotal"
            'invoiceamountpaid',                // for column: "InvoiceAmountPaid"
            'invoiceamountdue',                // for column: "InvoiceAmountDue"
            'inventoryitemcode',                // for column: "InventoryItemCode"
            'description',                // for column: "Description"
            'quantity',                // for column: "Quantity"
            'unitamount',                // for column: "UnitAmount"
            'discount',                // for column: "Discount"
            'lineamount',                // for column: "LineAmount"
            'accountcode',                // for column: "AccountCode"
            'taxtype',                // for column: "TaxType"
            'taxamount',                // for column: "TaxAmount"
            'trackingname1',                // for column: "TrackingName1"
            'trackingoption1',                // for column: "TrackingOption1"
            'trackingname2',                // for column: "TrackingName2"
            'trackingoption2',                // for column: "TrackingOption2"
            'currency',                // for column: "Currency"
            'type',                // for column: "Type"
            'sent',                // for column: "Sent"
            'status',                // for column: "Status"
        ];
    }

    toString() {
        return this.idAuto + ': ' + this.invoicenumber;
    }
}
