import { Component } from '@angular/core';
import { Validators } from '@angular/forms';
import { BaseFormComponent } from '../../../../shared/components/base-form/base-form.component';

@Component({
    selector: 'app-user-form',
    templateUrl: './form.component.html',
    styleUrls: ['./../../../../shared/grid/components/core-form/core-form.component.scss']
})
export class FormComponent extends BaseFormComponent {
    // @todo Validation rules
    fields = {
        id: ['', []],
        // name: ['', [Validators.required, Validators.minLength(3)]],
        // surname: ['', [Validators.required, Validators.minLength(3)]],
        username: ['', [Validators.required, Validators.minLength(3)]],
        email: ['', [Validators.required, Validators.minLength(3)]],
        password: ['', [Validators.required, Validators.minLength(3)]],
        password_repeat: ['', [Validators.required, Validators.minLength(3)]],
        role: ['', [Validators.required, Validators.minLength(3)]],
        country: ['', [Validators.required, Validators.minLength(2), Validators.maxLength(2)]],
        phone_number: ['', [Validators.required, Validators.minLength(6)]],
        // profile: ['', [Validators.required, Validators.minLength(3)]],
        // scope: ['', [Validators.required, Validators.minLength(3)]],
    };

    defaultRole = 'user';

    defaultCountry = 'AU';

    roles = [
      {
        label: 'Admin',
        name: 'Admin'
      },
      {
        label: 'Manager',
        name: 'Manager'
      },
      {
        label: 'User',
        name: 'User'
      }
    ];

    // Complete list from here: https://countrycode.org/
    countries = [
      {name: 'Afghanistan', code: '93', iso2: 'AF', iso3: 'AFG'},
      {name: 'Albania', code: '355', iso2: 'AL', iso3: 'ALB'},
      {name: 'Algeria', code: '213', iso2: 'DZ', iso3: 'DZA'},
      {name: 'American Samoa', code: '1-684', iso2: 'AS', iso3: 'ASM'},
      {name: 'Andorra', code: '376', iso2: 'AD', iso3: 'AND'},
      {name: 'Angola', code: '244', iso2: 'AO', iso3: 'AGO'},
      {name: 'Anguilla', code: '1-264', iso2: 'AI', iso3: 'AIA'},
      {name: 'Antarctica', code: '672', iso2: 'AQ', iso3: 'ATA'},
      {name: 'Antigua and Barbuda', code: '1-268', iso2: 'AG', iso3: 'ATG'},
      {name: 'Argentina', code: '54', iso2: 'AR', iso3: 'ARG'},
      {name: 'Armenia', code: '374', iso2: 'AM', iso3: 'ARM'},
      {name: 'Aruba', code: '297', iso2: 'AW', iso3: 'ABW'},
      {name: 'Australia', code: '61', iso2: 'AU', iso3: 'AUS'},
      {name: 'Austria', code: '43', iso2: 'AT', iso3: 'AUT'},
      {name: 'Azerbaijan', code: '994', iso2: 'AZ', iso3: 'AZE'},
      {name: 'Bahamas', code: '1-242', iso2: 'BS', iso3: 'BHS'},
      {name: 'Bahrain', code: '973', iso2: 'BH', iso3: 'BHR'},
      {name: 'Bangladesh', code: '880', iso2: 'BD', iso3: 'BGD'},
      {name: 'Barbados', code: '1-246', iso2: 'BB', iso3: 'BRB'},
      {name: 'Belarus', code: '375', iso2: 'BY', iso3: 'BLR'},
      {name: 'Belgium', code: '32', iso2: 'BE', iso3: 'BEL'},
      {name: 'Belize', code: '501', iso2: 'BZ', iso3: 'BLZ'},
      {name: 'Benin', code: '229', iso2: 'BJ', iso3: 'BEN'},
      {name: 'Bermuda', code: '1-441', iso2: 'BM', iso3: 'BMU'},
      {name: 'Bhutan', code: '975', iso2: 'BT', iso3: 'BTN'},
      {name: 'Bolivia', code: '591', iso2: 'BO', iso3: 'BOL'},
      {name: 'Bosnia and Herzegovina', code: '387', iso2: 'BA', iso3: 'BIH'},
      {name: 'Botswana', code: '267', iso2: 'BW', iso3: 'BWA'},
      {name: 'Brazil', code: '55', iso2: 'BR', iso3: 'BRA'},
      {name: 'British Indian Ocean Territory', code: '246', iso2: 'IO', iso3: 'IOT'},
      {name: 'British Virgin Islands', code: '1-284', iso2: 'VG', iso3: 'VGB'},
      {name: 'Brunei', code: '673', iso2: 'BN', iso3: 'BRN'},
      {name: 'Bulgaria', code: '359', iso2: 'BG', iso3: 'BGR'},
      {name: 'Burkina Faso', code: '226', iso2: 'BF', iso3: 'BFA'},
      {name: 'Myanmar', code: '95', iso2: 'MM', iso3: 'MMR'},
      {name: 'Burundi', code: '257', iso2: 'BI', iso3: 'BDI'},
      {name: 'Cambodia', code: '855', iso2: 'KH', iso3: 'KHM'},
      {name: 'Cameroon', code: '237', iso2: 'CM', iso3: 'CMR'},
      {name: 'Canada', code: '1', iso2: 'CA', iso3: 'CAN'},
      {name: 'Cape Verde', code: '238', iso2: 'CV', iso3: 'CPV'},
      {name: 'Cayman Islands', code: '1-345', iso2: 'KY', iso3: 'CYM'},
      {name: 'Central African Republic', code: '236', iso2: 'CF', iso3: 'CAF'},
      {name: 'Chad', code: '235', iso2: 'TD', iso3: 'TCD'},
      {name: 'Chile', code: '56', iso2: 'CL', iso3: 'CHL'},
      {name: 'China', code: '86', iso2: 'CN', iso3: 'CHN'},
      {name: 'Christmas Island', code: '61', iso2: 'CX', iso3: 'CXR'},
      {name: 'Cocos Islands', code: '61', iso2: 'CC', iso3: 'CCK'},
      {name: 'Colombia', code: '57', iso2: 'CO', iso3: 'COL'},
      {name: 'Comoros', code: '269', iso2: 'KM', iso3: 'COM'},
      {name: 'Republic of the Congo', code: '242', iso2: 'CG', iso3: 'COG'},
      {name: 'Democratic Republic of the Congo', code: '243', iso2: 'CD', iso3: 'COD'},
      {name: 'Cook Islands', code: '682', iso2: 'CK', iso3: 'COK'},
      {name: 'Costa Rica', code: '506', iso2: 'CR', iso3: 'CRI'},
      {name: 'Croatia', code: '385', iso2: 'HR', iso3: 'HRV'},
      {name: 'Cuba', code: '53', iso2: 'CU', iso3: 'CUB'},
      {name: 'Curacao', code: '599', iso2: 'CW', iso3: 'CUW'},
      {name: 'Cyprus', code: '357', iso2: 'CY', iso3: 'CYP'},
      {name: 'Czech Republic', code: '420', iso2: 'CZ', iso3: 'CZE'},
      {name: 'Denmark', code: '45', iso2: 'DK', iso3: 'DNK'},
      {name: 'Djibouti', code: '253', iso2: 'DJ', iso3: 'DJI'},
      {name: 'Dominica', code: '1-767', iso2: 'DM', iso3: 'DMA'},
      {name: 'Dominican Republic', code: '1-809, 1-829, 1-849', iso2: 'DO', iso3: 'DOM'},
      {name: 'East Timor', code: '670', iso2: 'TL', iso3: 'TLS'},
      {name: 'Ecuador', code: '593', iso2: 'EC', iso3: 'ECU'},
      {name: 'Egypt', code: '20', iso2: 'EG', iso3: 'EGY'},
      {name: 'El Salvador', code: '503', iso2: 'SV', iso3: 'SLV'},
      {name: 'Equatorial Guinea', code: '240', iso2: 'GQ', iso3: 'GNQ'},
      {name: 'Eritrea', code: '291', iso2: 'ER', iso3: 'ERI'},
      {name: 'Estonia', code: '372', iso2: 'EE', iso3: 'EST'},
      {name: 'Ethiopia', code: '251', iso2: 'ET', iso3: 'ETH'},
      {name: 'Falkland Islands', code: '500', iso2: 'FK', iso3: 'FLK'},
      {name: 'Faroe Islands', code: '298', iso2: 'FO', iso3: 'FRO'},
      {name: 'Fiji', code: '679', iso2: 'FJ', iso3: 'FJI'},
      {name: 'Finland', code: '358', iso2: 'FI', iso3: 'FIN'},
      {name: 'France', code: '33', iso2: 'FR', iso3: 'FRA'},
      {name: 'French Polynesia', code: '689', iso2: 'PF', iso3: 'PYF'},
      {name: 'Gabon', code: '241', iso2: 'GA', iso3: 'GAB'},
      {name: 'Gambia', code: '220', iso2: 'GM', iso3: 'GMB'},
      {name: 'Georgia', code: '995', iso2: 'GE', iso3: 'GEO'},
      {name: 'Germany', code: '49', iso2: 'DE', iso3: 'DEU'},
      {name: 'Ghana', code: '233', iso2: 'GH', iso3: 'GHA'},
      {name: 'Gibraltar', code: '350', iso2: 'GI', iso3: 'GIB'},
      {name: 'Greece', code: '30', iso2: 'GR', iso3: 'GRC'},
      {name: 'Greenland', code: '299', iso2: 'GL', iso3: 'GRL'},
      {name: 'Grenada', code: '1-473', iso2: 'GD', iso3: 'GRD'},
      {name: 'Guam', code: '1-671', iso2: 'GU', iso3: 'GUM'},
      {name: 'Guatemala', code: '502', iso2: 'GT', iso3: 'GTM'},
      {name: 'Guernsey', code: '44-1481', iso2: 'GG', iso3: 'GGY'},
      {name: 'Guinea', code: '224', iso2: 'GN', iso3: 'GIN'},
      {name: 'Guinea-Bissau', code: '245', iso2: 'GW', iso3: 'GNB'},
      {name: 'Guyana', code: '592', iso2: 'GY', iso3: 'GUY'},
      {name: 'Haiti', code: '509', iso2: 'HT', iso3: 'HTI'},
      {name: 'Honduras', code: '504', iso2: 'HN', iso3: 'HND'},
      {name: 'Hong Kong', code: '852', iso2: 'HK', iso3: 'HKG'},
      {name: 'Hungary', code: '36', iso2: 'HU', iso3: 'HUN'},
      {name: 'Iceland', code: '354', iso2: 'IS', iso3: 'ISL'},
      {name: 'India', code: '91', iso2: 'IN', iso3: 'IND'},
      {name: 'Indonesia', code: '62', iso2: 'ID', iso3: 'IDN'},
      {name: 'Iran', code: '98', iso2: 'IR', iso3: 'IRN'},
      {name: 'Iraq', code: '964', iso2: 'IQ', iso3: 'IRQ'},
      {name: 'Ireland', code: '353', iso2: 'IE', iso3: 'IRL'},
      {name: 'Isle of Man', code: '44-1624', iso2: 'IM', iso3: 'IMN'},
      {name: 'Israel', code: '972', iso2: 'IL', iso3: 'ISR'},
      {name: 'Italy', code: '39', iso2: 'IT', iso3: 'ITA'},
      {name: 'Ivory Coast', code: '225', iso2: 'CI', iso3: 'CIV'},
      {name: 'Jamaica', code: '1-876', iso2: 'JM', iso3: 'JAM'},
      {name: 'Japan', code: '81', iso2: 'JP', iso3: 'JPN'},
      {name: 'Jersey', code: '44-1534', iso2: 'JE', iso3: 'JEY'},
      {name: 'Jordan', code: '962', iso2: 'JO', iso3: 'JOR'},
      {name: 'Kazakhstan', code: '7', iso2: 'KZ', iso3: 'KAZ'},
      {name: 'Kenya', code: '254', iso2: 'KE', iso3: 'KEN'},
      {name: 'Kiribati', code: '686', iso2: 'KI', iso3: 'KIR'},
      {name: 'Kosovo', code: '383', iso2: 'XK', iso3: 'XKX'},
      {name: 'Kuwait', code: '965', iso2: 'KW', iso3: 'KWT'},
      {name: 'Kyrgyzstan', code: '996', iso2: 'KG', iso3: 'KGZ'},
      {name: 'Laos', code: '856', iso2: 'LA', iso3: 'LAO'},
      {name: 'Latvia', code: '371', iso2: 'LV', iso3: 'LVA'},
      {name: 'Lebanon', code: '961', iso2: 'LB', iso3: 'LBN'},
      {name: 'Lesotho', code: '266', iso2: 'LS', iso3: 'LSO'},
      {name: 'Liberia', code: '231', iso2: 'LR', iso3: 'LBR'},
      {name: 'Libya', code: '218', iso2: 'LY', iso3: 'LBY'},
      {name: 'Liechtenstein', code: '423', iso2: 'LI', iso3: 'LIE'},
      {name: 'Lithuania', code: '370', iso2: 'LT', iso3: 'LTU'},
      {name: 'Luxembourg', code: '352', iso2: 'LU', iso3: 'LUX'},
      {name: 'Macau', code: '853', iso2: 'MO', iso3: 'MAC'},
      {name: 'Macedonia', code: '389', iso2: 'MK', iso3: 'MKD'},
      {name: 'Madagascar', code: '261', iso2: 'MG', iso3: 'MDG'},
      {name: 'Malawi', code: '265', iso2: 'MW', iso3: 'MWI'},
      {name: 'Malaysia', code: '60', iso2: 'MY', iso3: 'MYS'},
      {name: 'Maldives', code: '960', iso2: 'MV', iso3: 'MDV'},
      {name: 'Mali', code: '223', iso2: 'ML', iso3: 'MLI'},
      {name: 'Malta', code: '356', iso2: 'MT', iso3: 'MLT'},
      {name: 'Marshall Islands', code: '692', iso2: 'MH', iso3: 'MHL'},
      {name: 'Mauritania', code: '222', iso2: 'MR', iso3: 'MRT'},
      {name: 'Mauritius', code: '230', iso2: 'MU', iso3: 'MUS'},
      {name: 'Mayotte', code: '262', iso2: 'YT', iso3: 'MYT'},
      {name: 'Mexico', code: '52', iso2: 'MX', iso3: 'MEX'},
      {name: 'Micronesia', code: '691', iso2: 'FM', iso3: 'FSM'},
      {name: 'Moldova', code: '373', iso2: 'MD', iso3: 'MDA'},
      {name: 'Monaco', code: '377', iso2: 'MC', iso3: 'MCO'},
      {name: 'Mongolia', code: '976', iso2: 'MN', iso3: 'MNG'},
      {name: 'Montenegro', code: '382', iso2: 'ME', iso3: 'MNE'},
      {name: 'Montserrat', code: '1-664', iso2: 'MS', iso3: 'MSR'},
      {name: 'Morocco', code: '212', iso2: 'MA', iso3: 'MAR'},
      {name: 'Mozambique', code: '258', iso2: 'MZ', iso3: 'MOZ'},
      {name: 'Namibia', code: '264', iso2: 'NA', iso3: 'NAM'},
      {name: 'Nauru', code: '674', iso2: 'NR', iso3: 'NRU'},
      {name: 'Nepal', code: '977', iso2: 'NP', iso3: 'NPL'},
      {name: 'Netherlands', code: '31', iso2: 'NL', iso3: 'NLD'},
      {name: 'Netherlands Antilles', code: '599', iso2: 'AN', iso3: 'ANT'},
      {name: 'New Caledonia', code: '687', iso2: 'NC', iso3: 'NCL'},
      {name: 'New Zealand', code: '64', iso2: 'NZ', iso3: 'NZL'},
      {name: 'Nicaragua', code: '505', iso2: 'NI', iso3: 'NIC'},
      {name: 'Niger', code: '227', iso2: 'NE', iso3: 'NER'},
      {name: 'Nigeria', code: '234', iso2: 'NG', iso3: 'NGA'},
      {name: 'Niue', code: '683', iso2: 'NU', iso3: 'NIU'},
      {name: 'Northern Mariana Islands', code: '1-670', iso2: 'MP', iso3: 'MNP'},
      {name: 'North Korea', code: '850', iso2: 'KP', iso3: 'PRK'},
      {name: 'Norway', code: '47', iso2: 'NO', iso3: 'NOR'},
      {name: 'Oman', code: '968', iso2: 'OM', iso3: 'OMN'},
      {name: 'Pakistan', code: '92', iso2: 'PK', iso3: 'PAK'},
      {name: 'Palau', code: '680', iso2: 'PW', iso3: 'PLW'},
      {name: 'Palestine', code: '970', iso2: 'PS', iso3: 'PSE'},
      {name: 'Panama', code: '507', iso2: 'PA', iso3: 'PAN'},
      {name: 'Papua New Guinea', code: '675', iso2: 'PG', iso3: 'PNG'},
      {name: 'Paraguay', code: '595', iso2: 'PY', iso3: 'PRY'},
      {name: 'Peru', code: '51', iso2: 'PE', iso3: 'PER'},
      {name: 'Philippines', code: '63', iso2: 'PH', iso3: 'PHL'},
      {name: 'Pitcairn', code: '64', iso2: 'PN', iso3: 'PCN'},
      {name: 'Poland', code: '48', iso2: 'PL', iso3: 'POL'},
      {name: 'Portugal', code: '351', iso2: 'PT', iso3: 'PRT'},
      {name: 'Puerto Rico', code: '1-787, 1-939', iso2: 'PR', iso3: 'PRI'},
      {name: 'Qatar', code: '974', iso2: 'QA', iso3: 'QAT'},
      {name: 'Reunion', code: '262', iso2: 'RE', iso3: 'REU'},
      {name: 'Romania', code: '40', iso2: 'RO', iso3: 'ROU'},
      {name: 'Russia', code: '7', iso2: 'RU', iso3: 'RUS'},
      {name: 'Rwanda', code: '250', iso2: 'RW', iso3: 'RWA'},
      {name: 'Saint Barthelemy', code: '590', iso2: 'BL', iso3: 'BLM'},
      {name: 'Samoa', code: '685', iso2: 'WS', iso3: 'WSM'},
      {name: 'San Marino', code: '378', iso2: 'SM', iso3: 'SMR'},
      {name: 'Sao Tome and Principe', code: '239', iso2: 'ST', iso3: 'STP'},
      {name: 'Saudi Arabia', code: '966', iso2: 'SA', iso3: 'SAU'},
      {name: 'Senegal', code: '221', iso2: 'SN', iso3: 'SEN'},
      {name: 'Serbia', code: '381', iso2: 'RS', iso3: 'SRB'},
      {name: 'Seychelles', code: '248', iso2: 'SC', iso3: 'SYC'},
      {name: 'Sierra Leone', code: '232', iso2: 'SL', iso3: 'SLE'},
      {name: 'Singapore', code: '65', iso2: 'SG', iso3: 'SGP'},
      {name: 'Sint Maarten', code: '1-721', iso2: 'SX', iso3: 'SXM'},
      {name: 'Slovakia', code: '421', iso2: 'SK', iso3: 'SVK'},
      {name: 'Slovenia', code: '386', iso2: 'SI', iso3: 'SVN'},
      {name: 'Solomon Islands', code: '677', iso2: 'SB', iso3: 'SLB'},
      {name: 'Somalia', code: '252', iso2: 'SO', iso3: 'SOM'},
      {name: 'South Africa', code: '27', iso2: 'ZA', iso3: 'ZAF'},
      {name: 'South Korea', code: '82', iso2: 'KR', iso3: 'KOR'},
      {name: 'South Sudan', code: '211', iso2: 'SS', iso3: 'SSD'},
      {name: 'Spain', code: '34', iso2: 'ES', iso3: 'ESP'},
      {name: 'Sri Lanka', code: '94', iso2: 'LK', iso3: 'LKA'},
      {name: 'Saint Helena', code: '290', iso2: 'SH', iso3: 'SHN'},
      {name: 'Saint Kitts and Nevis', code: '1-869', iso2: 'KN', iso3: 'KNA'},
      {name: 'Saint Lucia', code: '1-758', iso2: 'LC', iso3: 'LCA'},
      {name: 'Saint Martin', code: '590', iso2: 'MF', iso3: 'MAF'},
      {name: 'Saint Pierre and Miquelon', code: '508', iso2: 'PM', iso3: 'SPM'},
      {name: 'Saint Vincent and the Grenadines', code: '1-784', iso2: 'VC', iso3: 'VCT'},
      {name: 'Sudan', code: '249', iso2: 'SD', iso3: 'SDN'},
      {name: 'Suriname', code: '597', iso2: 'SR', iso3: 'SUR'},
      {name: 'Svalbard and Jan Mayen', code: '47', iso2: 'SJ', iso3: 'SJM'},
      {name: 'Swaziland', code: '268', iso2: 'SZ', iso3: 'SWZ'},
      {name: 'Sweden', code: '46', iso2: 'SE', iso3: 'SWE'},
      {name: 'Switzerland', code: '41', iso2: 'CH', iso3: 'CHE'},
      {name: 'Syria', code: '963', iso2: 'SY', iso3: 'SYR'},
      {name: 'Taiwan', code: '886', iso2: 'TW', iso3: 'TWN'},
      {name: 'Tajikistan', code: '992', iso2: 'TJ', iso3: 'TJK'},
      {name: 'Tanzania', code: '255', iso2: 'TZ', iso3: 'TZA'},
      {name: 'Thailand', code: '66', iso2: 'TH', iso3: 'THA'},
      {name: 'Togo', code: '228', iso2: 'TG', iso3: 'TGO'},
      {name: 'Tokelau', code: '690', iso2: 'TK', iso3: 'TKL'},
      {name: 'Tonga', code: '676', iso2: 'TO', iso3: 'TON'},
      {name: 'Trinidad and Tobago', code: '1-868', iso2: 'TT', iso3: 'TTO'},
      {name: 'Tunisia', code: '216', iso2: 'TN', iso3: 'TUN'},
      {name: 'Turkey', code: '90', iso2: 'TR', iso3: 'TUR'},
      {name: 'Turkmenistan', code: '993', iso2: 'TM', iso3: 'TKM'},
      {name: 'Turks and Caicos Islands', code: '1-649', iso2: 'TC', iso3: 'TCA'},
      {name: 'Tuvalu', code: '688', iso2: 'TV', iso3: 'TUV'},
      {name: 'United Arab Emirates', code: '971', iso2: 'AE', iso3: 'ARE'},
      {name: 'Uganda', code: '256', iso2: 'UG', iso3: 'UGA'},
      {name: 'United Kingdom', code: '44', iso2: 'GB', iso3: 'GBR'},
      {name: 'Ukraine', code: '380', iso2: 'UA', iso3: 'UKR'},
      {name: 'Uruguay', code: '598', iso2: 'UY', iso3: 'URY'},
      {name: 'United States', code: '1', iso2: 'US', iso3: 'USA'},
      {name: 'Uzbekistan', code: '998', iso2: 'UZ', iso3: 'UZB'},
      {name: 'Vanuatu', code: '678', iso2: 'VU', iso3: 'VUT'},
      {name: 'Vatican', code: '379', iso2: 'VA', iso3: 'VAT'},
      {name: 'Venezuela', code: '58', iso2: 'VE', iso3: 'VEN'},
      {name: 'Vietnam', code: '84', iso2: 'VN', iso3: 'VNM'},
      {name: 'U.S. Virgin Islands', code: '1-340', iso2: 'VI', iso3: 'VIR'},
      {name: 'Wallis and Futuna', code: '681', iso2: 'WF', iso3: 'WLF'},
      {name: 'Western Sahara', code: '212', iso2: 'EH', iso3: 'ESH'},
      {name: 'Yemen', code: '967', iso2: 'YE', iso3: 'YEM'},
      {name: 'Zambia', code: '260', iso2: 'ZM', iso3: 'ZMB'},
      {name: 'Zimbabwe', code: '263', iso2: 'ZW', iso3: 'ZWE'},
      {
        name: 'Other',
        iso2: 'OT',
        iso3: 'OTH',
        code: '',
      },
    ];

  save() {
    if (this.form.valid) {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      this.subscriptions.add(this.service.createUser(this.form.value).subscribe(data => {
          this.saving = true;
          this.notificationService.success('User created');
          this.location.back();
        },
        error => {
          console.log(error);
          this.notificationService.error('Unable to create new user');
        }));
    } else {
      alert('form invalid');
    }
  }
}
