import { AfterViewInit, Component, OnInit } from '@angular/core';
import { DataViewComponent } from '../../../../shared/grid/components/data-view/data-view.component';

@Component({
    selector: 'app-referral-form-view',
    templateUrl: '../../../../shared/grid/components/data-view/data-view.component.html',
    styleUrls: ['../../../../shared/grid/components/data-view/data-view.component.scss']
})
export class ViewComponent extends DataViewComponent implements OnInit {
    title = 'Referral Form';
    apiName = 'referral-form';

    displayedFields = [
        'id',                // for column: "id"
        'emailAddress',                // for column: "email_address"
        'firstNameOfReferrer',                // for column: "first_name_of_referrer"
        'lastNameOfReferrer',                // for column: "last_name_of_referrer"
        'referrerRelationship',                // for column: "referrer_relationship"
        'referrerPhone',                // for column: "referrer_phone"
        'fundsManagement',                // for column: "funds_management"
        'planManagementAgency',                // for column: "plan_management_agency"
        'planManagementContact',                // for column: "plan_management_contact"
        'agreedToPrivacyPolicy',                // for column: "agreed_to_privacy_policy"
        'agreedToProvidePersonalInfo',                // for column: "agreed_to_provide_personal_info"
        'participantFirstName',                // for column: "participant_first_name"
        'participantLastName',                // for column: "Participant Last Name"
        'participantPreferredFirstName',                // for column: "participant_preferred_first_name"
        'gender',                // for column: "Gender"
        'dateOfBirth',                // for column: "Date of Birth"
        'diagnosis',                // for column: "diagnosis"
        'behaviourHistory',                // for column: "behaviour_history"
        'theParticipantHasAHistoryOfTheFollowingBehaviours',                // for column: "The Participant has a history of the following behaviours:"
        'addressOfParticipant',                // for column: "Address of Participant"
        'postcodeOfParticipant',                // for column: "Postcode of Participant"
        'region',                // for column: "region"
        'participantCanConsentToServices',                // for column: "participant_can_consent_to_services"
        'ndisNumber',                // for column: "NDIS Number"
        'ndisStartDate',                // for column: "NDIS Start Date"
        'ndisEndDate',                // for column: "NDIS End Date"
        'personsNdisGoals',                // for column: "Person's NDIS goals"
        'ndisPlan',                // for column: "NDIS Plan"
        'lineItemToQuoteFrom',                // for column: "line_item_to_quote_from"
        'howMuchFundingIsInEachStatedSupport',                // for column: "How much funding is in each stated support"
        'supportEnvironments',                // for column: "Support Environments"
        'reasonForReferral',                // for column: "Reason for Referral"
        'hasRestrictedPractices',                // for column: "has_restricted_practices"
        'restrictivePracticesCurrentlyUsed',                // for column: "restrictive_practices_currently_used"
        'chemicalRestraintProtocol',                // for column: "chemical_restraint_protocol"
        'restrictivePracticesAllAuthorised',                // for column: "restrictive_practices_all_authorised"
        'rpaExpiryDates',                // for column: "rpa_expiry_dates"
        'currentRpaConsents',                // for column: "current_rpa_consents"
        'pleaseExplainWhyEachRestrictivePracticeIsNeeded',                // for column: "Please explain why each Restrictive Practice is needed"
        'iAmInterestedInTheFollowingServices',                // for column: "I am interested in the following services"
        'consenterFirstName',                // for column: "Consenter First Name"
        'consenterLastName',                // for column: "Consenter Last Name"
        'consenterPhoneNumber',                // for column: "Consenter Phone Number"
        'consenterAddress',                // for column: "Consenter Address"
        'consenterEmailAddress',                // for column: "Consenter Email Address"
        'consenterRelationshipToParticipanttickAllThatApply',                // for column: "Consenter Relationship to participant (tick all that apply)"
        'enterAlternativeConsenter',                // for column: "enter_alternative_consenter"
        'alternativeConsenterContactFirstName',                // for column: "Alternative Consenter/ Contact First Name"
        'alternativeConsenterContactPersonLastName',                // for column: "Alternative Consenter/ Contact Person Last Name"
        'alternativeConsenterContactPersonMobile',                // for column: "Alternative Consenter/ Contact Person Mobile"
        'alternativeConsenterContactPersonEmail',                // for column: "Alternative Consenter/ Contact Person Email"
        'alternativeConsenterContactPersonAddress',                // for column: "Alternative Consenter / Contact Person Address"
        'alternativeConsenterRelationship',                // for column: "alternative_consenter_relationship"
        'enterAccommodationContact',                // for column: "enter_accommodation_contact"
        'supportedAccommodationKeyContactName',                // for column: "Supported Accommodation Key Contact - Name"
        'supportedAccommodationKeyContactMobile',                // for column: "Supported Accommodation Key Contact - Mobile"
        'supportedAccommodationKeyContactEmail',                // for column: "Supported Accommodation Key Contact - Email"
        'enterDayProgramContact',                // for column: "enter_day_program_contact"
        'dayProgramKeyContactName',                // for column: "Day Program Key Contact - Name"
        'dayProgramKeyContactMobile',                // for column: "Day Program Key Contact - Mobile"
        'dayProgramKeyContactEmail',                // for column: "Day Program Key Contact - Email"
        'enterEmployerContact',                // for column: "enter_employer_contact"
        'employmentKeyContactName',                // for column: "Employment Key Contact - Name"
        'employmentKeyContactMobile',                // for column: "Employment Key Contact - Mobile"
        'employmentKeyContactEmail',                // for column: "Employment Key Contact - Email"
        'additionalInfo',                // for column: "additional_info"
        'serviceBookingConsent',                // for column: "service_booking_consent"
        'timestamp',                // for column: "Timestamp"
        'token',                // for column: "Token"
    ];
}
